# Generated by Django 5.0.6 on 2024-05-20 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='card.card'),
        ),
    ]
