# Generated by Django 5.0.6 on 2024-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_alter_section_password'),
        ('user', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='users', to='section.section'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
