# Generated by Django 5.0.6 on 2024-05-20 20:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '0001_initial'),
        ('user', '0002_user_card_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=240)),
                ('esn_price', models.DecimalField(decimal_places=2, max_digits=240)),
                ('location', models.CharField(max_length=255)),
                ('location_url', models.URLField()),
                ('type', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('publish_date', models.DateTimeField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
