# Generated by Django 5.0.6 on 2024-05-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('section', '0004_alter_section_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='section.section'),
        ),
    ]
