# Generated by Django 5.0.6 on 2024-05-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_event_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
