# Generated by Django 5.0.6 on 2024-05-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_section_description_section_section_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='country_code',
            field=models.CharField(default='SI', max_length=3),
        ),
        migrations.AlterField(
            model_name='section',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
