# Generated by Django 5.0.6 on 2024-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_section_country_code_alter_section_location_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
