# Generated by Django 5.0.6 on 2024-06-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticket_event_id_alter_ticket_issued_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='qr_code_image',
        ),
    ]
