# Generated by Django 5.0.6 on 2024-06-03 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_location_url'),
        ('feedback', '0002_alter_feedback_id'),
        ('user', '0006_user_sections_alter_user_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('user', 'event')},
        ),
    ]
