# Generated by Django 5.0.6 on 2024-05-20 20:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255)),
                ('expiration_date', models.DateField()),
                ('activation_date', models.DateField()),
            ],
        ),
    ]
